version: '3.9'

services:
  mysql:
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Tmc1480
      - TZ=America/Mexico_City
